name: lint

on:
  pull_request:
    branches:
      - "main"

jobs:
  code_lint:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3
        # Setup which version of Python to use
      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install the package using the setup.py
      - name: Lint Check
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ""
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--ignore=E501"
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
  
  commit_lint:
    name: Conventional Commit Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Lint
        uses: webiny/action-conventional-commits@v1.1.0